"""Agent-related runtime services."""

from shinbot.agent.context import ActiveContextPool, ContextManager
from shinbot.agent.model_runtime import (
    EmbedResult,
    GenerateResult,
    ModelCallError,
    ModelRuntime,
    ModelRuntimeCall,
)
from shinbot.agent.prompting import (
    ContextStrategy,
    ContextStrategyBudget,
    PromptAssemblyRequest,
    PromptAssemblyResult,
    PromptComponent,
    PromptComponentKind,
    PromptComponentRecord,
    PromptLogger,
    PromptLoggerRecord,
    PromptProfile,
    PromptRegistry,
    PromptSnapshot,
    PromptSource,
    PromptSourceType,
    PromptStage,
    PromptStageBlock,
)
from shinbot.agent.runtime import AgentRuntime
from shinbot.agent.tools import (
    ToolCallRequest,
    ToolCallResult,
    ToolDefinition,
    ToolExecutionContext,
    ToolManager,
    ToolOwnerType,
    ToolRegistry,
    ToolRiskLevel,
    ToolVisibility,
)

__all__ = [
    "ActiveContextPool",
    "AgentRuntime",
    "ContextManager",
    "EmbedResult",
    "GenerateResult",
    "ModelCallError",
    "ModelRuntime",
    "ModelRuntimeCall",
    "ContextStrategy",
    "ContextStrategyBudget",
    "PromptAssemblyRequest",
    "PromptAssemblyResult",
    "PromptComponent",
    "PromptComponentKind",
    "PromptComponentRecord",
    "PromptLogger",
    "PromptLoggerRecord",
    "PromptProfile",
    "PromptRegistry",
    "PromptSnapshot",
    "PromptSource",
    "PromptSourceType",
    "PromptStage",
    "PromptStageBlock",
    "ToolCallRequest",
    "ToolCallResult",
    "ToolDefinition",
    "ToolExecutionContext",
    "ToolManager",
    "ToolOwnerType",
    "ToolRegistry",
    "ToolRiskLevel",
    "ToolVisibility",
]
